spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost/final_exam?characterEncoding=utf-8&useSSL=false
    password: root12345


spring.mustache.suffix: .html